import assert from "node:assert/strict";
import { after, before, it } from "node:test";
import { installBrowserGlobals } from "../../helpers/stub-browser-globals.js";
import { installToastPainter } from "../../../src/core/user-prompts.js";
const restore = installBrowserGlobals();
after(() => { restore(); installToastPainter(null); });
let CameraRawDialog;
before(async () => { ({ CameraRawDialog } = await import("../../../src/ui/dialogs/camera-raw-dialog.js")); });
it("drops decoded sensor state and tells the developing panel to release its buffers", () => {
  const dialog = Object.create(CameraRawDialog.prototype);
  let released = 0;
  dialog.cameraMetadata = {};
  dialog.decodedRaw = { linearRgbBuffer: new Float32Array(3) };
  dialog.previewDownsampleFactor = 3;
  dialog.developPanel = { releaseRawSource: () => { released++; } };
  dialog.releaseDecodedRaw();
  assert.equal(dialog.cameraMetadata, null);
  assert.equal(dialog.decodedRaw, null);
  assert.equal(dialog.previewDownsampleFactor, 0);
  assert.equal(released, 1);
});
it("updates preview budgets on resize and only rebuilds a decoded image", () => {
  const dialog = Object.create(CameraRawDialog.prototype), calls = [];
  dialog.developPanel = { resize: (...args) => calls.push(args) };
  dialog.rebuildPreviewPlateIfFactorChanged = () => calls.push("rebuild");
  dialog.resize(500, 80);
  assert.equal(dialog.previewBudgetWidth, 240);
  assert.equal(dialog.previewBudgetHeight, 160);
  assert.deepEqual(calls, [[500, 80]]);
  dialog.decodedRaw = {};
  dialog.resize(1200, 700);
  assert.equal(dialog.previewBudgetWidth, 880);
  assert.equal(dialog.previewBudgetHeight, 700);
  assert.deepEqual(calls.slice(1), [[1200, 700], "rebuild"]);
});
it("reports develop failure and retains the open dialog for retry without allocating an image", () => {
  const dialog = Object.create(CameraRawDialog.prototype), notifications = [];
  installToastPainter((...args) => notifications.push(args));
  const rawState = { linearRgbBuffer: new Float32Array(3) };
  dialog.decodedRaw = rawState;
  dialog.developFullResolution = () => { throw new Error("invalid camera metadata"); };
  dialog.close = () => assert.fail("a failed develop must leave the dialog open");
  dialog.dispatch = () => assert.fail("a failed develop must not focus a document");
  dialog.onOK();
  assert.equal(dialog.decodedRaw, rawState);
  assert.equal(notifications.length, 1);
  assert.match(notifications[0][0], /Camera Raw could not develop this image: Error: invalid camera metadata/);
  assert.equal(notifications[0][1], 7000);
});
it("avoids rebuilding the preview when the downsample factor has not changed", () => {
  const dialog = Object.create(CameraRawDialog.prototype);
  dialog.decodedRaw = { rawWidth: 8, rawHeight: 6 };
  dialog.previewBudgetWidth = 4;
  dialog.previewBudgetHeight = 3;
  dialog.previewDownsampleFactor = 2;
  dialog.developPanel = { setValue: () => assert.fail("unchanged factor must not reset settings") };
  dialog.rebuildPreviewPlateIfFactorChanged();
  assert.equal(dialog.previewDownsampleFactor, 2);
});
